### ISSUE TITLE
Configure CI/CD Pipeline

### ISSUE THREAD

**Issue by samueldaviddelacruz** [samueldaviddelacruz/go-job-board#3]
Need to configure CI/CD pipeline for easier deployment and maintainability over time

- [x] Configure docker/docker compose for the different part of the applications.
- [x] Config Travis CI to run tests for PRs.
- [x] Config Travis CI for CD to Heroku.

**Comment by GabrielBB** [comment]
You could algo use GitHub Actions

**Comment by samueldaviddelacruz** [comment]
> You could algo use GitHub Actions

that would be a good idea, but as of the time of this post, github action its pretty new and not many people handle it well (me included), which would delay the first deploy since there will be a learning curve involved, but the idea is not discarded for the future.
